
name: DbUp CI
on:
  push: { branches: [ "main" ] }
  workflow_dispatch: {}
jobs:
  migrate:
    runs-on: ubuntu-latest
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: "Y"
          MSSQL_SA_PASSWORD: ${{ secrets.MSSQL_SA_PASSWORD }}
        ports: [ "1433:1433" ]
        options: >-
          --health-cmd="bash -c 'echo > /dev/tcp/127.0.0.1/1433 || exit 1'"
          --health-interval=10s --health-timeout=5s --health-retries=10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: "8.0.x" }
      - name: Ejecutar migraciones (DbUp)
        env:
          CONNECTION_STRING: "Server=127.0.0.1,1433;Initial Catalog=migraciondb;User ID=sa;Password=${{ secrets.MSSQL_SA_PASSWORD }};Encrypt=True;TrustServerCertificate=True"
        run: |
          dotnet restore
          dotnet build -c Release --no-restore
          # Deja SOLO UNA línea, según tu ruta real:
          dotnet run -c Release --project ./MigradorDbUp/MigradorDbUp.csproj -- --ci | tee migrations.log
          # dotnet run -c Release --project ./MigradorDbUp/MigradorDbUp/MigradorDbUp.csproj -- --ci | tee migrations.log
      - uses: actions/upload-artifact@v4
        with: { name: dbup-log, path: migrations.log }
